apiVersion: v2
name: mongodb
description: MongoDB Replica Set using Bitnami chart
type: application
version: 1.0.0
appVersion: "5.0"

dependencies:
  - name: mongodb
    version: "13.18.5"
    repository: "https://charts.bitnami.com/bitnami"
