image:
  repository: mongo
  tag: "5"
  pullPolicy: IfNotPresent

service:
  port: 27017

storage:
  size: 1Gi
  storageClassName: gp2-immediate

auth:
  username: admin
  password: password123
  database: tasksdb

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
