httpRoute:
  enabled: false

mongodb:
  architecture: replicaset
  replicaCount: 3
  fullnameOverride: mongodb-service

  auth:
    enabled: true
    rootUser: admin
    rootPassword: password123
    databases:
      - tasksdb
    usernames:
      - admin
    passwords:
      - password123

  persistence:
    enabled: true
    storageClass: gp2-immediate
    size: 1Gi

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi