replicaCount: 1

image:
  repository: mongo
  tag: "6.0"
  pullPolicy: IfNotPresent

persistence:
  storageClass: gp2-immediate
  size: 1Gi

auth:
  rootUser: admin
  rootPassword: password123

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
