replicaCount: 1

image:
  repository: aishwini08/backend
  pullPolicy: Always
<<<<<<< HEAD
<<<<<<< HEAD
  tag: 70
=======
  tag: 70
>>>>>>> 9ac65c42e37451c996f36825ce8fcc20e3db8f32
=======
  tag: 70
>>>>>>> bd4abdc57df587f96cd06712cb05955bbb4e104f

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 5000

env:
  - name: MONGO_CONN_STR
    value: "mongodb://admin:password123@mongodb-service:27017/tasksdb?authSource=admin"
  - name: PORT
    value: "5000"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
  - name: gateway
    sectionName: http
  hostnames:
  - chart-example.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers

resources: {}

livenessProbe:
  httpGet:
    path: /healthz
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
