apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-arbiter
  namespace: three-tier
spec:
  serviceName: mongodb-arbiter
  replicas: 1

  selector:
    matchLabels:
      app: mongodb-arbiter

  template:
    metadata:
      labels:
        app: mongodb-arbiter

    spec:

      # Keep arbiter on a different worker node
      # from the MongoDB data replicas
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - mongodb
              topologyKey: kubernetes.io/hostname

      # Try to keep the arbiter in a different AZ
      # from the MongoDB data replicas
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - mongodb
                  - mongodb-arbiter

      # Fix MongoDB keyfile permissions
      initContainers:
        - name: fix-keyfile-perms
          image: busybox
          command:
            - sh
            - -c
            - >
              cp /keyfile-secret/keyfile /keyfile/keyfile &&
              chmod 400 /keyfile/keyfile &&
              chown 999:999 /keyfile/keyfile

          volumeMounts:
            - name: keyfile-secret
              mountPath: /keyfile-secret

            - name: keyfile
              mountPath: /keyfile

      # MongoDB arbiter
      containers:
        - name: mongodb-arbiter
          image: mongo:6.0

          args:
            - "--replSet"
            - "rs0"
            - "--bind_ip_all"
            - "--port"
            - "27017"
            - "--keyFile"
            - "/keyfile/keyfile"

          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi

          volumeMounts:
            - name: keyfile
              mountPath: /keyfile

      volumes:
        - name: keyfile-secret
          secret:
            secretName: mongodb-keyfile

        - name: keyfile
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-arbiter
  namespace: three-tier
spec:
  clusterIP: None

  selector:
    app: mongodb-arbiter

  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017