server:
  service:
    # LoadBalancer creates an AWS ELB so you can access the ArgoCD UI
    type: LoadBalancer

  extraArgs:
    - --insecure   

configs:
  params:
    server.insecure: "true"   

  secret:
    argocdServerAdminPassword: ""   

global:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
